services:
  uwsgi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - socket_volume:/tmp
    networks:
      - app_net
    depends_on:
      - opensearch
      - redis

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - socket_volume:/tmp
    depends_on:
      - uwsgi
    networks:
      - app_net

  opensearch:
    build:
      context: ./opensearch
      dockerfile: Dockerfile
    env_file:
      - ./opensearch/.env
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - app_net

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

    networks:
      - app_net

volumes:
  socket_volume:

networks:
  app_net:
    driver: bridge